export default GenreCode = [
  {"Pop":POP},
  {"Hip Hop Rap":HIP_HOP_RAP},
  {"Dance":DANCE},
  {"Electronic":ELECTRONIC},
  {"Soul RNB":SOUL_RNB},
  {"Altenative":ALTERNATIVE},
  {"Rock":ROCK},
  {"Latin":LATIN},
  {"Film TV":FILM_TV},
  {"Country":COUNTRY},
  {"Afro Beats":AFRO_BEATS},
  {"Wordlwide":WORLDWIDE},
  {"Reggae Dance Hall":REGGAE_DANCE_HALL},
  {"House":HOUSE},
  {"K Pop":K_POP},
  {"French Pop":FRENCH_POP},
  {"Singer Songwriter":SINGER_SONGWRITER},
  {"Reg Mexico":REG_MEXICO},
];