import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useDispatch, useSelector } from "react-redux";

import { useGetExploreQuery } from './api/spotifyAPI';

import SongCard from '@/components/SongCard';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data, isFetching, error} = useGetExploreQuery();

  console.log(data);
  if(!data) return console.log(error)
  return (
    <>
      <Head>
        <title>Music Web app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='pb-20'>
        <div className="grid gap-4 grid-cols-2  md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-7  h-full">
          {data.map((item, key) => (
            <SongCard item={item} key={key} />
          ))}
        </div>
      </main>
    </>
  );
}
